sudo: required
services:
  - docker

before_install: 
  - docker build -t kiminoto1412/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kiminoto1412/react-test npm test

after_success: 
  - docker build -t kiminoto1412/multi-client ./client
  - docker build -t kiminoto1412/multi-nginx ./nginx
  - docker build -t kiminoto1412/multi-server ./server
  - docker build -t kiminoto1412/multi-worker ./worker