sudo: required
services:
  - docker

before_install: 
  - docker build -t kiminoto1412/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kiminoto1412/react-test npm test

after_success: 
  - docker build -t kiminoto1412/multi-client ./client
  - docker build -t kiminoto1412/multi-nginx ./nginx
  - docker build -t kiminoto1412/multi-server ./server
  - docker build -t kiminoto1412/multi-worker ./worker
  # Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push to docker hub
  - docker push kiminoto1412/multi-client 
  - docker push kiminoto1412/multi-nginx 
  - docker push kiminoto1412/multi-server 
  - docker push kiminoto1412/multi-worker 